name: pomodoro
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.0
  - pip:
    - streamlit==1.31.1
    - playsound==1.3.0
    - pillow==10.1.0
    - pandas==2.1.1
    - altair==5.1.2 